# -*- coding: utf-8 -*-
"""Group_21_BDMHAssigment1_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxzY0lT6SwJp8GjYtTxsYpx96lzpzHCw

**BDMH_Assignment1: Predicting stage of liver cancer patients.**

mounting google drive:
"""

from google.colab import drive
drive.mount('/content/drive')

"""Importing module description:"""

import pandas as pd
import numpy as np
import sys
import os
from sklearn.ensemble import RandomForestClassifier as rf

"""Hyperparameter tuning:"""

from sklearn.model_selection import GridSearchCV,\
RandomizedSearchCV

param_grid = {
    'n_estimators': [35],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [4],
    'max_leaf_nodes': [12],
}

"""Reading the training dataset file (kaggle_train):"""

df1 = pd.read_csv("/content/drive/My Drive/Group_21/kaggle_train.csv")

"""Removing the column named "Labels":"""

df1.drop(columns=['Labels'],inplace=True)

"""Showing first 5 records of updated dataset:"""

df1.head()

"""Fetching only the "Labels" column from the training dataset and saving the "Labels" column as the last column of the dataset."""

df2 = pd.read_csv('/content/drive/My Drive/Group_21/kaggle_train.csv')

df1['Labels'] = df2['Labels']

"""Now again checking the resultant dataset, here we get the "Labels" column as the last column."""

df1.head()

"""Using RandomForestClassifier as machine learning model to train the dataset:"""

# grid_search = GridSearchCV(rf(),param_grid=param_grid)
# grid_search.fit(df1.iloc[:,:-1],df1.iloc[:,-1])
# print(grid_search.best_estimator_)
clf = rf(random_state=42, n_estimators=800)
clf.fit(df1.iloc[:,:-1],df1.iloc[:,-1])

"""At this point, we have a trained Random Forest model, but we need to find out whether it is making accurate predictions."""

pd.DataFrame(clf.predict_proba(df1.iloc[:,:-1])[:,1])

"""Reading the test dataset file (kaggle_test) and fetching top five records:"""

df3 = pd.read_csv("/content/drive/My Drive/Group_21/kaggle_test.csv")
df3.head()

"""Removing the ID column from the original dataset (df3):"""

df3.drop(columns=['ID'],inplace=True)

"""Feature engineering on test dataset:"""

df3.head()
print(df3.shape)

"""Fetching the top five rows of the test dataset:"""

df3

"""Prediction for test dataset:"""

df4 = pd.DataFrame(clf.predict_proba(df3)[:,1])

"""Giving ID on output file as give format in sample file(1000 onwards):"""

dd = []
for i in range(len(df4)):
    dd.append(1000+i+1)
df4['ID'] = dd

"""Two columns ('Lables', 'ID') required for output file:"""

df4.columns = ['Labels','ID']

"""df4 is final dataset for output file:"""

df4 = df4[['ID','Labels']]

"""Converting df4 dataset to 'Kaggle_output.csv' file:"""

df4.to_csv('/content/drive/My Drive/Group_21/Kaggle_output.csv', index=None)

"""Showing the output:"""

df4